version: 2.1
executors:
  exectr:
    docker:
      - image: yevheniiandrus/leetcode:latest
jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup gtest child repo
          command: |
            cd third_party
            git submodule init
            git submodule update 
      - run:
          name: Setup cmake and build artifacts
          command: |
            cd FibonacciNumber
            mkdir build
            cd build
            cmake ..
            make
      - persist_to_workspace:
          root: .
          paths: FibonacciNumber/build
  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd FibonacciNumber/build
            ./tests --gtest_output=XML
      - store_test_results:
          path: FibonacciNumber/build
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
